apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idaten-storage
  namespace: idaten
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
